Korean translation polishment
bui/taiko-web pull request #323
Opened 2021-02-04 13:17 UTC by jerrybeomsoo

- Polished existing Korean translation which could be misleading
- Translated several strings that were not previously in Korean

2021-02-04 13:42 UTC, LoveEevee requested changes

2021-02-04 13:42 UTC, LoveEevee commented on public/src/js/strings.js
> +		ko: "오니"
The Extreme difficulty in the korean releases of taiko on switch and ps4 is called 귀신, only official names are allowed so please change this back

2021-02-04 13:42 UTC, LoveEevee commented on public/src/js/strings.js
> +		ko: "가사 포함됨"
Google tells me 포함됨 is a typo and should be 포함된 instead

2021-02-04 13:50 UTC, jerrybeomsoo commented on public/src/js/strings.js
> +		ko: "오니"
Reverted in commit.

2021-02-04 13:51 UTC, jerrybeomsoo commented on public/src/js/strings.js
> +		ko: "가사 포함됨"
It is actually not a typo nor gramatically incorrect, and "포함됨" is more natural.

2021-02-04 13:52 UTC, LoveEevee approved these changes

2021-02-05 17:21 UTC, merged

2021-02-05 17:21 UTC, bui commented
Thanks!