Add Traditional Chinese translation
bui/taiko-web pull request #374
Opened 2021-06-06 09:12 UTC by SiderealArt

2021-06-06 12:30 UTC, SiderealArt commented on public/src/js/strings.js
> +				tw: "延遲校準",
After looking at the game settings, I guess we can just use 延遲 here.

2021-06-06 12:32 UTC, SiderealArt commented on public/src/js/strings.js
> +				tw: "自動延遲校準",
Ok. I'll change it. Thanks for checking.

2021-06-06 12:43 UTC, SiderealArt commented on public/src/js/strings.js
> +			tw: "驗證失敗：%s"
I think using 失敗 will make it sound more natural.

2021-06-06 12:48 UTC, LoveEevee commented on public/src/js/strings.js
> +				tw: "自動延遲校準",
Please also change lines 829 and 891 in that case, so that they are consistent with this change

2021-06-06 12:57 UTC, SiderealArt commented on public/src/js/strings.js
> +				tw: "自動延遲校準",
Finished!

2021-06-06 13:06 UTC, LoveEevee requested changes

2021-06-06 13:06 UTC, LoveEevee commented on public/src/js/strings.js
> +			tw: "記得附上下方的診斷資料！"
A comma is missing at the end of this line

2021-06-06 13:26 UTC, LoveEevee commented
21 strings are still untranslated, do you want to leave them in english
```
loadSongError
calibration.audioHelp.content
calibration.audioHelp.contentAlt
calibration.videoHelp.content
account.newPasswordsDoNotMatch
account.displayName
account.verifyPassword
serverError (8 trings)
browserSupport (4 strings)
customSongs.description
gpicker.cookieError
```

2021-06-06 16:17 UTC, SiderealArt commented
There's some string I'm not sure or can't find a proper way to translate. I'll just leave them and let other people help.

2021-06-06 16:46 UTC, LoveEevee commented on public/src/js/strings.js
> +			tw: "無法使用此密碼，請確認您的新密碼的長度大於 6 個字"
It should be "at least 6 characters"/"6 characters or more" instead of "more than 6 characters"
(I am using online translation to verify)

2021-06-06 18:11 UTC, LoveEevee approved these changes

2021-07-11 05:42 UTC, 269Seahorse approved these changes
These strings do work well

2021-08-17 12:44 UTC, Nyaasu66 commented on public/src/js/strings.js
> +				tw: "延遲校準",
The reason my Simplified Chinese translation does not use 'delay' but 'delayed calibration' is that I think the original English menu name is inaccurately written, because this menu directory is including the function of manual calibration and excellent auto-assisted calibration. So although the Chinese translation literally does not match the original meaning, it is more appropriate here. Thank you @Loveevee for your careful and conscientious proofreading, you are a very qualified and excellent open source contributor!

> (Translated with www.DeepL.com/Translator)

2021-08-17 13:12 UTC, SiderealArt commented on public/src/js/strings.js
> +				tw: "延遲校準",
I think @Nyaasu66 got a point there. I'll change the translation back to "延遲校準" then.

2022-02-03 11:55 UTC, merged